draft analysis plan for group to review
nipraxis-summer-2023/diagnostics-bold_but_better pull request #24
Opened 2023-09-05 16:43 UTC by hveravallaskreppur

Hey @itsharveen @kaushik-pallavi 

as per the homework, please see a draft analysis plan here. I think we can discuss the plan with comments to the PR itself, does that make sense?

I've got a question about the project: @matthew-brett 
(I tried asking "at" nipraxis-summer-2023 but that gave a github error)

- is there any benchmark dataset we can use to evaluate our outlier detection methods?

2023-09-05 16:51 UTC, matthew-brett commented
Hi - did you try @nipraxis-summer-2023/instructors ?

That's a good question - we don't offer you a benchmark dataset - but such datasets do exist.   For example you may consider the quality control data sets in this special issue:  https://www.frontiersin.org/research-topics/33922/demonstrating-quality-control-qc-procedures-in-fmri#articles

@oesteban @effigies - any thoughts?

2023-09-07 09:54 UTC, itsharveen requested changes

2023-09-07 09:54 UTC, itsharveen commented on analysis_plan.md
> +1. decide on which outlier methods to use (apart from mean and DIVARs)
```suggestion
1. complete initial research on which outlier methods are used in fmri data prep -> take notes in shared google doc
2. decide on which outlier methods to use (apart from mean and DIVARs)
```

2023-09-07 12:36 UTC, kaushik-pallavi approved these changes

2023-09-07 12:36 UTC, merged

2023-09-07 12:43 UTC, hveravallaskreppur commented
@nipraxis-summer-2023/instructors - this plan is now ready for review.